### ISSUE TITLE
Unable to unzip downloaded model

### ISSUE THREAD

**Issue by ehof** [VemundFredriksen/LungTumorMask#6]
Observed on Ubuntu 20.04 and Python 3.8.10.

```
Loading model...
Traceback (most recent call last):
  File "/home/fraxinus/Fraxinus/medtekAI/medtekAI/Docker-DeepSintef/venv/bin/lungtumormask", line 8, in <module>
    sys.exit(main())
  File "/home/fraxinus/Fraxinus/medtekAI/medtekAI/Docker-DeepSintef/venv/lib/python3.8/site-packages/lungtumormask/__main__.py", line 20, in main
    mask.mask(args.input, args.output)
  File "/home/fraxinus/Fraxinus/medtekAI/medtekAI/Docker-DeepSintef/venv/lib/python3.8/site-packages/lungtumormask/mask.py", line 20, in mask
    model = load_model()
  File "/home/fraxinus/Fraxinus/medtekAI/medtekAI/Docker-DeepSintef/venv/lib/python3.8/site-packages/lungtumormask/mask.py", line 13, in load_model
    state_dict = T.hub.load_state_dict_from_url("https://github.com/VemundFredriksen/LungTumorMask/releases/download/0.0/dc_student.pth", progress=True, map_location=gpu_device)
  File "/home/fraxinus/Fraxinus/medtekAI/medtekAI/Docker-DeepSintef/venv/lib/python3.8/site-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile

```

**Comment by andreped** [comment]
Fixed in ab9d51080886f5b5a3012ee66564bd646fef2016.

It was due to some dependency versioning being too lenient.
